[2024-10-22T14:46:51.066+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-22T14:46:51.089+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:46:50.240025+00:00 [queued]>
[2024-10-22T14:46:51.094+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:46:50.240025+00:00 [queued]>
[2024-10-22T14:46:51.095+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-22T14:46:51.103+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract_data_wiki> on 2024-10-22 14:46:50.240025+00:00
[2024-10-22T14:46:51.111+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_football', 'extract_data_wiki', 'manual__2024-10-22T14:46:50.240025+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/dag_football.py', '--cfg-path', '/tmp/tmpwf5imo2u']
[2024-10-22T14:46:51.112+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=2337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-22T14:46:51.112+0000] {standard_task_runner.py:91} INFO - Job 8: Subtask extract_data_wiki
[2024-10-22T14:46:51.113+0000] {standard_task_runner.py:64} INFO - Started process 2401 to run task
[2024-10-22T14:46:51.142+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_football.extract_data_wiki manual__2024-10-22T14:46:50.240025+00:00 [running]> on host 884be59c9e77
[2024-10-22T14:46:51.189+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Karan' AIRFLOW_CTX_DAG_ID='dag_football' AIRFLOW_CTX_TASK_ID='extract_data_wiki' AIRFLOW_CTX_EXECUTION_DATE='2024-10-22T14:46:50.240025+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-22T14:46:50.240025+00:00'
[2024-10-22T14:46:51.191+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-22T14:46:51.326+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/urllib3/connectionpool.py:1100 InsecureRequestWarning: Unverified HTTPS request is being made to host 'en.wikipedia.org'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
[2024-10-22T14:46:51.717+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-22T14:46:51.718+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/src/get_wiki_data.py", line 15, in get_wiki_data
    table = soup.find_all("table",attrs={"class":"wikitable sortable sticky-header jquery-tablesorter"})[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[2024-10-22T14:46:51.726+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dag_football, task_id=extract_data_wiki, run_id=manual__2024-10-22T14:46:50.240025+00:00, execution_date=20241022T144650, start_date=20241022T144651, end_date=20241022T144651
[2024-10-22T14:46:51.733+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8 for task extract_data_wiki (list index out of range; 2401)
[2024-10-22T14:46:51.767+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-10-22T14:46:51.778+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-22T14:46:51.779+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
